resource_types:
- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: repo-release
  type: github-release
  check_every: 168h
  source:
    access_token: ((git-release-token))
    owner: OdekoTeam
    repository: graphql-engine
- name: repo
  webhook_token: ((github-webhook-token))
  type: git
  check_every: 1h
  source:
    branch: master
    password: ((git-release-token))
    uri: https://github.com/OdekoTeam/graphql-engine.git
    username: ((git-user))
- name: master-image
  type: docker-image
  source:
    repository: docker.odeko.com/odeko/graphql-engine
- name: concourse
  type: git
  check_every: 1h
  source:
    branch: master
    password: ((git-release-token))
    uri: https://github.com/OdekoTeam/concourse.git
    username: ((git-user))
- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-build-webhook-token))

jobs:
- name: test
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: repo
      trigger: true
    - get: concourse
  - task: install-and-test
    privileged: true
    file: concourse/tasks/haskell/test/default.yml
  on_failure:
    do:
    - task: slack-message
      file: concourse/tasks/common/slack_master_message.yml
    - put: slack-alert
      params:
        username: 'concourse'
        icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
        text_file: slack-message/slack-info
        text: |
          :red_circle: *${BUILD_PIPELINE_NAME} job ${BUILD_JOB_NAME}/${BUILD_NAME} failed*
          See <https://concourse.odeko.com/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|concourse> for more information.
          $TEXT_FILE_CONTENT
        silent: true
- name: build-image
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: repo
      passed:
      - test
      trigger: true
    - get: concourse
  - task: get-version
    file: concourse/tasks/haskell/get-version/default.yml
  - task: build-executable
    privileged: true
    file: concourse/tasks/haskell/build/executable.yml
  - put: master-image
    params:
      build: repo-executable
      tag_file: repo-version/VERSION
      build_args_file: repo-executable/BUILD_ARGS
  on_failure:
    do:
    - task: slack-message
      file: concourse/tasks/common/slack_master_message.yml
    - put: slack-alert
      params:
        username: 'concourse'
        icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
        text_file: slack-message/slack-info
        text: |
          :red_circle: *${BUILD_PIPELINE_NAME} job ${BUILD_JOB_NAME}/${BUILD_NAME} failed*
          See <https://concourse.odeko.com/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|concourse> for more information.
          $TEXT_FILE_CONTENT
        silent: true
- name: git-release
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: repo
      passed:
      - test
      - build-image
      trigger: true
    - get: concourse
  - task: get-version
    file: concourse/tasks/haskell/get-version/default.yml
  - put: repo-release
    params:
      name: repo-version/VERSION
      tag: repo-version/VERSION
  on_failure:
    do:
    - task: slack-message
      file: concourse/tasks/common/slack_master_message.yml
    - put: slack-alert
      params:
        username: 'concourse'
        icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
        text_file: slack-message/slack-info
        text: |
          :red_circle: *${BUILD_PIPELINE_NAME} job ${BUILD_JOB_NAME}/${BUILD_NAME} failed*
          See <https://concourse.odeko.com/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|concourse> for more information.
          $TEXT_FILE_CONTENT
        silent: true
  on_success:
    do:
    - task: slack-message
      file: concourse/tasks/common/slack_master_message.yml
    - put: slack-alert
      params:
        username: 'concourse'
        icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
        text_file: slack-message/slack-info
        text: |
          :thumbsup: *${BUILD_PIPELINE_NAME} job ${BUILD_JOB_NAME}/${BUILD_NAME} succeeded*
          See <https://concourse.odeko.com/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|concourse> for more information.
          $TEXT_FILE_CONTENT
        silent: true
